version: '3'

services:
  chat:
    container_name: chat
    image: ghcr.io/swuecho/chat:latest # or use tag for better stability, e.g.v0.0.3
    expose:
      - 8080
    ports:
      # vist at http://your_host:8080 or http://your_host:8080/static/
      - 8080:8080
      # If you serve https:
      - 443:443
    environment:
      # at least one key is required.
      # !!! no quote aroud key !!!
      - OPENAI_API_KEY=thisisopenaikey # do not change if you do not have openai api key
      - CLAUDE_API_KEY=thisisclaudekey # do not change if you do not have claude api key
      # api call in 10min
      # set this to zero if your server is in public network. only increase ratelimit in admin panel for trusted users.
      - OPENAI_RATELIMIT=100
      # DB config, set based on your db config if you don't use the db in docker-compose
      - PG_HOST=db
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASS=thisisapassword
      - PG_PORT=5432
      ## IF YOU Server HTTPS, START ###
      - HTTPS=true
      - CERT_FILE=name_of_cert_file
      - KEY_FILE=name_of_key_file
      ## IF YOU Server HTTPS, END ###
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    restart: always
    user: postgres
    environment:
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "thisisapassword"
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
